### ISSUE TITLE
Check for existance of an example?

### ISSUE THREAD

**Issue by soniakeys** [exercism/v2-configlet#1]
A couple times now I've accidentally named an example program <problem>.go, especially if i've been alternately solving and developing, and then pushed.  Travis hasn't complained, I think indicating configlet isn't checking for this.  I haven't studied the configlet code yet but it seems it would be good if it complained if there were no example program, likely indicating it was misnamed.

**Comment by kytrinyx** [comment]
Yeah, configlet doesn't check for this, but probably should. Excellent suggestion! I'm on it :)

**Comment by kytrinyx** [comment]
Update: This uncovered several problems in existing repositories where the example file was named for the problem. Thanks for the suggestion!
