### ISSUE TITLE
Verify the presence of metadata files (description.md, metadata.yml) for all exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-configlet#10]
If the directory (slug) of an exercise is misspelled, or if the exercise implementation gets merged before the metadata makes it into x-common, then some of the endpoints blow up.

A recent example (but certainly not the first!) is `sublist` which got added to the Swift track in https://github.com/exercism/xswift/pull/222 with the slug `sub-list`.

The endpoint http://x.exercism.io/problems lists all of the valid problem descriptions, including the `slug`.

We should have a boolean flag that we can pass to turn it off (so that if you don't have an internet connection you can still check everything else). Then all the CI jobs that run `configlet` without any options will have the flag turned on, and would catch the problem.

**Comment by Insti** [comment]
The list of valid problems doesn't change that frequently, so it should be possible to check against an included list of problems and only ask the api if an unknown problem is found.

**Comment by kytrinyx** [comment]
Yeah, that's a good idea. It would be simple enough to generate a simple text list that can be included and easily updated. I like it.

**Comment by kytrinyx** [comment]
A quick note: the metadata files might be within the `exercises/:slug/.meta/` directory, or they might be in the `problem-specifications` repository.

I changed the title of this issue—missing metadata files would catch typos, but it would also catch (literally) missing metadata files :)

If we're feeling particularly clever, we could even make suggestions... _did you mean X?_... if there are any slugs that are very similar.

**Comment by kytrinyx** [comment]
Thinking more about this, I think that the best approach is to handle a `--spec-path` flag which tells configlet where the problem-specifications repository is checked out.

If there is no problem-specifications directory at the `spec-path` (e.g. in CI) we can `git clone --depth 1 https://github.com/exercism/problem-specifications.git` to that location.

**Comment by nywilken** [comment]
I believe this is issue has been addressed, but want to confirm before closing.

**Comment by kytrinyx** [comment]
Yepp, I checked everything before we released.
