### ISSUE TITLE
lint: invalid UUIDs seem to pass

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-configlet#100]
In exercism/haskell#601 there has been an invalid UUID introduced into the JSON:

```json
      "uuid": "40d4bb98-2e4a-4579-810e-g1230bc158e9",
```

You see the ``g`` beginning the last group? As far as I understand wikipedia, it should be hexadecimal notation, and therefore only ``0-9`` and ``a-f`` are allowed.

> In its canonical textual representation, the sixteen octets of a UUID are represented as 32 hexadecimal (base 16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 alphanumeric characters and four hyphens).

**Comment by nywilken** [comment]
@NobbZ thanks for opening this issue. It looks like it directly relates to #99 

Do you mind if I close this issue and track it with #99 ?

**Comment by NobbZ** [comment]
No, it is not a problem for me…

Duplicate of #99
