### ISSUE TITLE
Update Track READMEs

### ISSUE THREAD

**Issue by nywilken** [exercism/v2-configlet#116]
Before releasing the next version of Configlet the following tracks need to updated with README files for each exercise. See #98 for more information. 

- [x] tracks/haxe                                                                                                                                                                             
- [x] tracks/php                                                                                                                                                                              
- [x] tracks/python                                                                                                                                                                           
- [x] tracks/crystal                                                                                                                                                                          
- [x] tracks/swift                                                                                                                                                                            
- [x] tracks/elm                                                                                                                                                                              
- [x] tracks/go                                                                                                                                                                               
- [x] tracks/plsql                                                                                                                                                                            
- [x] tracks/csharp                                                                                                                                                       
- [x] tracks/objective-c 

_Edit: copy/pasting the details here for easy reference —kytrinyx_

```
ERROR: tracks/haxe
-> The implementation for 'leap' is missing a README.
ERROR: tracks/php
-> The implementation for 'flatten-array' is missing a README.
-> The implementation for 'collatz-conjecture' is missing a README.
-> The implementation for 'crypto-square' is missing a README.
-> The implementation for 'transpose' is missing a README.
ERROR: tracks/python
-> The implementation for 'bowling' is missing a README.
ERROR: tracks/crystal
-> The implementation for 'triangle' is missing a README.
ERROR: tracks/swift
-> The implementation for 'rotational-cipher' is missing a README.
ERROR: tracks/elm
-> The implementation for 'collatz-conjecture' is missing a README.
ERROR: tracks/go
-> The implementation for 'armstrong-numbers' is missing a README.
ERROR: tracks/plsql
-> The implementation for 'hello-world' is missing a README.
ERROR: tracks/csharp
-> The implementation for 'complex-numbers' is missing a README.
ERROR: tracks/objective-c
-> The implementation for 'collatz-conjecture' is missing a README.
-> The implementation for 'grains' is missing a README.
-> The implementation for 'say' is missing a README.
-> The implementation for 'nth-prime' is missing a README.
-> The implementation for 'two-fer' is missing a README.
```

**Comment by kytrinyx** [comment]
@nywilken I've updated all the tracks to add the missing READMEs. I'm going to close this... would you have time to cut the release?

**Comment by nywilken** [comment]
@kytrinyx thanks for handling the README updates. I have time to cut a release. I'll bump the version to 3.7.0 and update the changelog. If I run into any issues I'll be sure to ping the thread.

**Comment by nywilken** [comment]
@kytrinyx the latest release is now available for [download](https://github.com/exercism/configlet/releases/tag/v3.7.0). Thanks again for pushing the README updates along so quickly. 🙏

**Comment by kytrinyx** [comment]
@nywilken Fabulous! I'm so glad we've gotten this pushed forward. It feels really nice to be able to close out old, ongoing work.
