### ISSUE TITLE
fmt: Missing newline at end of files

### ISSUE THREAD

**Issue by paulgoetze** [exercism/v2-configlet#128]
Running `configlet fmt <file>` with v3.9.0 results in files not ending in a newline.

Reformatted files should end in a newline to make them POSIX compliant textfiles.
See https://github.com/exercism/erlang/pull/244#issuecomment-388557811

**Comment by kytrinyx** [comment]
I published a new release: https://github.com/exercism/configlet/releases/tag/v3.9.1
