### ISSUE TITLE
configlet lint raises error if `checklist_issue` contains a number

### ISSUE THREAD

**Issue by m-dango** [exercism/v2-configlet#136]
Saw the issue flagged in https://github.com/exercism/powershell/issues/69 and was having the same problem on perl6. If `checklist_issue` contains a number the following error occurs:
`-> invalid config config.json -- json: cannot unmarshal number into Go struct field Config.checklist_issue of type string`.

This is new to `v3.9.1` and does not occur in `v3.9.0`.

**Comment by nywilken** [comment]
@mienaikage thanks for reporting. Looking a little deeper into how the API is using this value it should be an int and not a string. The field is not implemented by a lot of tracks so this issue has not come up. Nor was it being tracked in v3.9.0

@kytrinyx when I spot checked I didn’t run into an issue, but looking at the tracks I tested against they don’t have a checklist issue. Th majority of tracks using this field have a number so we should change before trying to reformat those configs. 

Also if you can give me a little more context on the checklist issue field I can also update the documentation.

**Comment by kytrinyx** [comment]
The `checklist_issue` field holds the number of the tracking issue for upcoming tracks, which is used to say "if you want to help launch it, look here". If the `checklist_issue` is number 1, then we don't put it in the config. For the past two years, I have been bootstrapping tracks with a script, which means that the checklist issue is always 1. This field will go away.

The following tracks have one:
```
./haxe/config.json:  "checklist_issue": 2,
./vbnet/config.json:  "checklist_issue": 3,
./bash/config.json:  "checklist_issue": 4,
./powershell/config.json:  "checklist_issue": "4",
./perl6/config.json:  "checklist_issue": 30,
./sml/config.json:  "checklist_issue": 8,
./groovy/config.json:  "checklist_issue": 9,
./d/config.json:  "checklist_issue": 6,
```

I agree that we should make this an int.
