### ISSUE TITLE
Check for track specific metadata files.

### ISSUE THREAD

**Issue by Insti** [exercism/v2-configlet#15]
Where tracks implement track specific problems, configlet should check that the metadata is valid (or at least exists).

Related: #10 

See also: https://github.com/exercism/trackler/issues/45

**Comment by kytrinyx** [comment]
The trick here is that we don't check for the validity of the problem slug at all at the moment. We should, but I don't much like the idea of relying on calls over the network, and configlet will need to talk to the API to get a list of the available problems. The only way we'll know it's track-specific is if the slug doesn't match a problem from the common pool.

**Comment by kytrinyx** [comment]
I've updated #10 such that it encompasses this issue as well. Closing this in favor of the other.
