### ISSUE TITLE
Check for duplicate uuids (accounting for whitespace)

### ISSUE THREAD

**Issue by benreyn** [exercism/v2-configlet#162]
Recently on the elisp track we had a uuid accidentally munged in a PR that was not caught in code review. The long and short of it is that an existing exercise ended up with the same uuid as the new exercise that was being added. (plus some whitespace)

https://github.com/exercism/elisp/commit/62075c8884e55c362de10a717bfae2bd45361ea9#diff-06b2d3b23dce96e1619d2b53d6c947ec

This feels like a thing that configlet should be able to check for and we can run as a part of our CI workflow.

Ref conversation around incident in slack:
https://exercism-team.slack.com/archives/CASLG8D61/p1559859099000400

Ref original bug report:
https://github.com/exercism/exercism/issues/4882

cc: @iHiD @vermiculus @kytrinyx

**Comment by iHiD** [comment]
Thank you 💙

**Comment by kytrinyx** [comment]
Configlet should definitely be able to catch that! I'll take a look at this as soon as possible.

**Comment by rpottsoh** [comment]
It catches dupes just fine, but if one has a trailing space it won't.....

**Comment by petertseng** [comment]
according to https://github.com/petertseng/exercism-problem-specifications/blob/list-tracks/uuid.rb, the list of duplicate UUIDs currently:

dup 98ae146a-67f9-49ae-9cd6-00882a374248 [["groovy", "resistor-color-duo"], ["dart", "resistor-color-duo"]]
dup c52dfe2b-5634-4c0c-8ea2-3ca86e5d9a33 [["groovy", "isbn-verifier"], ["dart", "isbn-verifier"]]
dup b306bdaa-438e-46a2-ba54-82cb2c0be882 [["ruby", "allergies"], ["crystal", "allergies"]]
dup 00c6f623-2e54-4f90-ae3f-07e493f93c7c [["ruby", "protein-translation"], ["crystal", "protein-translation"]]
dup aeaed0e4-0973-4035-8bc5-07480849048f [["java", "tree-building"], ["python", "tree-building"]]

**Comment by iHiD** [comment]
@petertseng This is extremely helpful. Thank you.
@kytrinyx Could you update configlet for this pls?

I will put an hour aside to deal with all these.

**Comment by petertseng** [comment]
I seem to have misunderstood this issue and posted my above list in the wrong place. I now see that this issue is for two exercises in the same track, whereas I mistakenly posted a list concerning exercises in different tracks. If there needs to be a different issue, I would gladly move my list there instead of here. Apologies for reading too fast and thus misunderstanding.

**Comment by petertseng** [comment]
If I understand https://github.com/exercism/website/pull/601 correctly, it is now OK for two **different** tracks to share UUIDs.

~~If that is true, no action needs to be taken as a result of my above list. Apologies again for barking up the wrong tree.~~

~~I will now hide my unactionable list as off-topic. The discussion in this issue should return to the original issue which is two exercises in the **same** track.~~

**Comment by petertseng** [comment]
I will hide my incorrect list as off-topic.

**Comment by iHiD** [comment]
@petertseng I think what you've said here is still important, so I'd like to enforce this regardless. `uuid`s should be unique across exercism, so where our tooling can help with that I'd like it to. However, it seems you're right that that PR does remove the immediate danger.

**Comment by ee7** [comment]
I noticed this recently.

Just in case it's useful: see below for an updated list of duplicate UUIDs.

The most recent one is from today, introduced by Kotlin's `diffie-hellman`.

### Ordered by UUID:

| UUID                                  | Track      | Slug                |
| ------------------------------------- | ---------- | ------------------- |
| 00c6f623-2e54-4f90-ae3f-07e493f93c7c  | crystal    | protein-translation | 
|                                       | ruby       | protein-translation | 
|                                       |            |                     |  
| 50c34698-7767-42b3-962f-21c735e49787  | dart       | beer-song           |     
|                                       | ruby       | beer-song           |     
|                                       |            |                     |  
| 7c8294ee-5924-4bf8-a72f-31d0e2d7d9a0  | java       | leap                |     
|                                       | javascript | leap                |             
|                                       |            |                     |  
| 98ae146a-67f9-49ae-9cd6-00882a374248  | dart       | resistor-color-duo  |     
|                                       | groovy     | resistor-color-duo  |     
|                                       |            |                     |      
| 9b191b2f-b1a4-4c0e-b911-36666bff614d  | java       | diffie-hellman      |     
|                                       | kotlin     | diffie-hellman      |     
|                                       |            |                     |                  
| ac179b77-98a5-4daf-9773-3d68b6cd8548  | bash       | knapsack            | 
|                                       | java       | knapsack            | 
|                                       |            |                     |                          
| aeaed0e4-0973-4035-8bc5-07480849048f  | java       | tree-building       |     
|                                       | python     | tree-building       |     
|                                       |            |                     |  
| b306bdaa-438e-46a2-ba54-82cb2c0be882  | crystal    | allergies           | 
|                                       | ruby       | allergies           | 
|                                                    |                     |      
| c52dfe2b-5634-4c0c-8ea2-3ca86e5d9a33  | dart       | isbn-verifier       | 
|                                       | groovy     | isbn-verifier       |    


### Ordered by track:

| Track      | Slug                | UUID                                 |
| ---------- | ------------------- | ------------------------------------ |
| bash       | knapsack            | ac179b77-98a5-4daf-9773-3d68b6cd8548 |
| crystal    | allergies           | b306bdaa-438e-46a2-ba54-82cb2c0be882 |
| crystal    | protein-translation | 00c6f623-2e54-4f90-ae3f-07e493f93c7c |
| dart       | beer-song           | 50c34698-7767-42b3-962f-21c735e49787 |
| dart       | isbn-verifier       | c52dfe2b-5634-4c0c-8ea2-3ca86e5d9a33 |
| dart       | resistor-color-duo  | 98ae146a-67f9-49ae-9cd6-00882a374248 |
| groovy     | isbn-verifier       | c52dfe2b-5634-4c0c-8ea2-3ca86e5d9a33 |
| groovy     | resistor-color-duo  | 98ae146a-67f9-49ae-9cd6-00882a374248 |
| java       | diffie-hellman      | 9b191b2f-b1a4-4c0e-b911-36666bff614d |
| java       | knapsack            | ac179b77-98a5-4daf-9773-3d68b6cd8548 |
| java       | leap                | 7c8294ee-5924-4bf8-a72f-31d0e2d7d9a0 |
| java       | tree-building       | aeaed0e4-0973-4035-8bc5-07480849048f |
| javascript | leap                | 7c8294ee-5924-4bf8-a72f-31d0e2d7d9a0 |
| kotlin     | diffie-hellman      | 9b191b2f-b1a4-4c0e-b911-36666bff614d |
| python     | tree-building       | aeaed0e4-0973-4035-8bc5-07480849048f |
| ruby       | allergies           | b306bdaa-438e-46a2-ba54-82cb2c0be882 |
| ruby       | beer-song           | 50c34698-7767-42b3-962f-21c735e49787 |
| ruby       | protein-translation | 00c6f623-2e54-4f90-ae3f-07e493f93c7c |

**Comment by iHiD** [comment]
Thank you. 

@ekingery - Maybe this is something you could take a look at?
