### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by tqa236** [exercism/v2-configlet#170]
I'm sorry if I seriously miss it, but is there an installation guide for the configlet, ideally in README?

**Comment by ekingery** [comment]
Hello. There is no installation guide at the moment, just a link at the end of the README to the releases page: https://github.com/exercism/configlet/releases

If you download the release archive corresponding to your computer, it will contain a binary / executable file. Run that and you should be off to the races. Feel free to close if you feel that is sufficient, open a PR if you'd like to augment the README, or we can leave this open as a future TODO.

**Comment by tqa236** [comment]
Thank you. I manage to do that now so I will close this issue. I still hope that we will get clear instructions for installation in the future.
