### ISSUE TITLE
Investigate: what would it look like to lint the JSON format of config.json?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-configlet#18]
We want to normalize the JSON so that we can script changes to it without adding a lot of whitespace noise.

**Comment by robphoenix** [comment]
So far I've not found a JSON linter written in Go. I did wonder if we could just re-marshall the verified Config using `MarshallIndent`, see https://github.com/robphoenix/configlet/commit/de28dc124b10a462db3013799bf6d93b7505af1f, and then re-write the output back to file, but of course it wouldn't be included in the commit, would it? And it wouldn't output any response indicating whitespace inconsistencies travis could fail on.

Will this require writing a JSON linter in Go, or will it just need to check that each line is appropriately indented? How full featured does it need to be? How much is taken care of by unmarshalling the file into the appropriate struct?

**Comment by kytrinyx** [comment]
We could add a separate command to `configlet` that you can run locally before committing (kind of like `gofmt` but for `config.json`)

**Comment by robphoenix** [comment]
That would work. Would it be run by maintainers every now and then, or suggested to contributors in track README's perhaps? I'll send a PR later this week, or would it better to wait for #23 (which I've been meaning to properly read through, having been wrestling with Cobra myself recently)

**Comment by kytrinyx** [comment]
I think that if we use it, we should suggest that it be used by both contributors and maintainers whenever the config.json gets changed.

We should totally wait for #23 to land. I'm waiting on one last PR to be merged—all the 60+ other PRs that this one is relying on have been merged. I'll ping them (again).

**Comment by robphoenix** [comment]
Grand, I'll familiarize myself with #23 and work on a PR to implement what I've outlined above.

**Comment by kytrinyx** [comment]
Alrighty, #23 has landed!

You should be able to generate a new command with `cobra`, e.g. `cobra add fmt`, which will add a new file `cmd/fmt.go`, which in turn creates a new command `configlet fmt`. (Delete all the extraneous comments, license annotations, etc, they're just a distraction).

**Comment by kytrinyx** [comment]
Oh, also: you can load up a config file with `track.NewConfig(pathToTrack)`. Check out https://github.com/exercism/configlet/blob/master/track/config_test.go

**Comment by robphoenix** [comment]
Cool, thanks @kytrinyx I can't get to this until Tuesday at the earliest, but I'll aim to get something here for review next week.

**Comment by kytrinyx** [comment]
@robphoenix that sounds great, thank you!
