### ISSUE TITLE
Print error message if problem-specifications is not found

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-configlet#27]
Present README.md looks like [this](https://github.com/exercism/delphi/blob/master/exercises/wordy/README.md).

New README.md looks like [this](https://github.com/rpottsoh/exercism-delphi/blob/configletWordyREADME/exercises/wordy/README.md).

Should all the information regarding the problem be removed from the resulting README.md file?  Is there something that I should change in [exercise_readme.go.tmpl](https://github.com/exercism/delphi/blob/master/config/exercise_readme.go.tmpl)?

**Comment by kytrinyx** [comment]
It's missing the `problem-specifications` repository. Do you have that checked out locally?

The docs are here: https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md

If problem-specifications is not checked out where expected, then you can specify exactly where with the flag `--spec-path`:

```
configlet generate . --spec-path ../../problem-specifications # or whatever
```

**Comment by kytrinyx** [comment]
We should probably loud noises if configlet is trying to generate new READMEs without problem-specifications being checked out.

**Comment by rpottsoh** [comment]
I have problem-specifications checked out, but configlet will never find it.  I'll try your suggestion. 

Sent from my android device.

**Comment by rpottsoh** [comment]
Thanks @kytrinyx, specifying the path is what I needed.
