### ISSUE TITLE
Update lint command: verify that each exercise has a UUID

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-configlet#28]
When verifying the `config.json` for a track, each exercise is expected to have a UUID.

If it does not, the command should output an error message that explains that exercise `$SLUG` does not have a UUID.

**Comment by nywilken** [comment]
I think that #28 and #29 can be treated as one. If we rephrase #28 so that it reads something like 'Update lint command: verify that each exercise has a unique UUID'. Thoughts?

**Comment by kytrinyx** [comment]
We could, but the tasks are quite different from each other. One is a very quick, low-level check that is likely to catch the most common type of error (copy/paste within the same repository). The other requires a call across the wire.

If you want to tackle them, feel free to do so in a single PR.

**Comment by nywilken** [comment]
Ah okay so the expectation for #28 is that when checking for missing UUIDs within a track it would hit the API for validation, is that correct? 

If so that would imply that some how the config.json got corrupted (e.g the uuid for exercise Clock went missing) and that we should use the stored uuid returned from the API as the suggestion; otherwise if it truly doesn't exist, for the exercise, then suggest a newly generated uuid. 

Where as #29 is a simple duplicate check for the config.json as it is, correct?

Please let me know if I'm on the right track or completely off. 

Nonetheless, I would like to work on these two issues to familiarize myself with the uuid process and API endpoints. Let me know if it's cool to assign to myself or if I should wait for you to officially assign me. Thanks.

**Comment by kytrinyx** [comment]
I just realized I mis-remembered what 28 was about and didn't properly read-through before answering before. They're still different problems and should be reported separately.

> Nonetheless, I would like to work on these two issues to familiarize myself with the uuid process and API endpoints.

That's great, go ahead and assign yourself to both.

> If so that would imply that some how the config.json got corrupted (e.g the uuid for exercise Clock went missing) and that we should use the stored uuid returned from the API as the suggestion;

I don't think we'll ever be missing UUIDs on existing/old exercises. I would expect people to forget to add a UUID when adding a new exercise.

If it gets deleted, then that would be visible in the diff of the PR, and should get addressed (though a broken build in that case is nice and helpful).

#29 is actually two things:

1. a duplicate check within the `config.json` to catch copy/paste errors (I actually mis-read earlier about what 28 is about and thought it was about this)
2. a check across the wire to make sure that none of the UUIDs in this track are already in use in another track (e.g. if someone implemented "bob" in a new track and copied over the JSON from another track, we should get an error).

I think it might be worth reporting these last two separately to the user rather than conflating them, but I don't actually know. You'll probably have thoughts about that when you get to tackling the issue.

**Comment by nywilken** [comment]
@kytrinyx it doesn't seem like I have the ability to assign to myself. Can you please assign #28 and #29 to me, thanks.

**Comment by kytrinyx** [comment]
Done! I've also created a specific team for configlet and added you and @robphoenix to it. You both have push access, and can assign things to yourselves.

**Comment by nywilken** [comment]
Awesome, thank you. Working with this project has been such a great experience 🎉

**Comment by kytrinyx** [comment]
It's so lovely to have you along!

**Comment by robphoenix** [comment]
Oh cool, thanks! It's been so good having a proper back and forth review on my code for the `fmt` PR, really appreciate both of your time & effort.

**Comment by kytrinyx** [comment]
There's something magical, I find, about having three people who are all knee-deep in making something better.

With two it can be great, but there's always a time when someone's away or their head is in a different place and it's hard to think properly about whatever the other one is proposing.

But with three, suddenly everyone is catching different things, and the ideas bounce off each other, and things get so much better.

If y'all are up to looking at the stuff that's happening in the CLI repo as well, it could only be better for your input: https://github.com/exercism/cli/pulls
