### ISSUE TITLE
Possible graph/tree command

### ISSUE THREAD

**Issue by robphoenix** [exercism/v2-configlet#33]
@jonmcalder has done some [awesome work](https://github.com/exercism/discussions/issues/175#issuecomment-318243990) visualizing the graph of exercise dependencies in a `config.json`.

I wonder if it would be beneficial to add a graph command that could output something similar.

As Jon has used R it would have to be recreated in Go. I imagine this could be done by looping over the slice of `ExerciseMetadata` in a `Config` struct and building up the graph. This could then be used to possibly either output  a [graphviz](http://graphviz.org/About.php) dot file, using [this library](https://github.com/awalterschulze/gographviz) or building a web page, perhaps using [d3.js](https://d3js.org/)?

**Comment by kytrinyx** [comment]
I think this would be tremendously valuable.

**Comment by robphoenix** [comment]
Reading @iHiD's [comment](https://github.com/exercism/discussions/issues/175#issuecomment-318368925) perhaps a simple terminal output similar to Linux's `tree` command might be better?

```
.
├── hello-world
│   ├── leap
│   ├── gigasecond
│   └── clock
├── bob
├── beer-song
├── luhn
└── meetup
    ├── hamming
    ├── grains
    │   ├── raindrop
    │   └── forth
    └── house

13 exercises, 5 core
```

Would probably be easier to implement than what I've outlined above.

**Comment by kytrinyx** [comment]
A tree-like view would probably be easier to implement—and I think it would probably be a good, understandable visual, as well.

**Comment by robphoenix** [comment]
Okay, grand, I'll get on it.

**Comment by tleen** [comment]
:laughing:  Now that we are actually starting to analyze the layout of the Go track I came here to suggest this as an option for configlet. A co-maintainer beat be to it!

Looks like configlet may be becoming a more general purpose config-analyzer. If so I believe another helpful view of config would be a listing (and count) of exercises by difficulty.

**Comment by kytrinyx** [comment]
> If so I believe another helpful view of config would be a listing (and count) of exercises by difficulty.

Yeah, Configlet is turning into our all-purpose track maintenance tool. Go ahead and open up the issue for the exercise list, and we can dig into the details of it.

**Comment by tleen** [comment]
Will do. It may be a nice option in the tree view to have the difficulty next to the exercise:

```text
└── meetup (3)
    ├── hamming (5)
    ├── grains (7)
```

**Comment by robphoenix** [comment]
This is a great idea @tleen!
