### ISSUE TITLE
Update lint command: verify the format of the maintainers file

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-configlet#35]
We've added a config/maintainers.json file: https://github.com/exercism/docs/blob/master/maintaining-a-track/maintainer-configuration.md

If the file is present, we should make sure that the JSON is valid.

**Comment by robphoenix** [comment]
Is this closed by https://github.com/exercism/configlet/commit/7c4c2e87b7618df2675d5a10782647ac122e12ae?

**Comment by kytrinyx** [comment]
Whoops. Yes, it is. Thanks :)
