### ISSUE TITLE
Update lint command: verify that core exercises are never unlocked by other exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-configlet#39]
Per @jonmcalder's (fabulous) comment here: https://github.com/exercism/discussions/issues/175#issuecomment-319067625 we should probably do some linting for the track progression logic.

If an exercise is `core` it should not be `unlocked_by` another exercise.

**Comment by robphoenix** [comment]
Also from https://github.com/exercism/r/commit/f1decd2996a170386a075e323d9cbd6dce7e5b31 this should check that all exercises are unlocked by a valid exercise, though it wouldn't necessarily need to be core.
