### ISSUE TITLE
"help lint" response should be updated.

### ISSUE THREAD

**Issue by rpottsoh** [exercism/v2-configlet#42]
Present output of Configlet to command `help lint` as v3.2.0.
```
Verify that the config.json file is valid, and that the exercises are complete.

Call lint command with path to track:

  configlet lint path/to/track

Usage:
  configlet lint [flags]

Flags:
  -h, --help   help for lint
```
As of v3.2.0 `lint` is now verifying that `config/maintainers.json` is valid JSON.  Should the help response from configlet convey this?
```
Verify that the config.json file is valid, and that the exercises are complete.
Verify that the maintainers.json is valid JSON.

Call lint command with path to track:

  configlet lint path/to/track

Usage:
  configlet lint [flags]

Flags:
  -h, --help   help for lint
```

**Comment by kytrinyx** [comment]
> As of v3.2.0 lint is now verifying that config/maintainers.json is valid JSON. Should the help response from configlet convey this?

It sure should!

**Comment by robphoenix** [comment]
I'll fix this today unless either of you have already started? 
https://github.com/exercism/configlet/pull/45/commits/605c03c19d67b66be87e9ffdb8c0cc8ab894633c is overriding part of the above help output, so I want to make sure that's doing what it should be doing, and that it's the best way.
