### ISSUE TITLE
How soon should regeneration of READMEs pick up upstream changes?

### ISSUE THREAD

**Issue by stkent** [exercism/v2-configlet#58]
This PR was merged a few days ago:

https://github.com/exercism/problem-specifications/pull/880

I used configlet 3.3.0 to regenerate the `space-age` README in the Kotlin track today. The new content from the PR referenced above was not included in the newly-generated README. (There was a whitespace change, so I know that regeneration happened).

Am I misunderstanding how configlet sources copy for the template?

**Comment by kytrinyx** [comment]
> I used configlet 3.3.0 to regenerate the space-age README in the Kotlin track today.

Was the problem-specifications repo that you had locally up to date with the upstream?

**Comment by stkent** [comment]
It was not. Does that copy have to be in a special location relative to the track directory, or do I pass a path to problem-specifications somehow?

**Comment by nywilken** [comment]
> Does that copy have to be in a special location relative to the track directory, or do I pass a path to problem-specifications somehow?

Configlet expects the problem-specifications directory to be in the same root directory as the track directory. For example:

```
/root/path/
-- erlang/
-- problem-specifications/
```

Or you can use the` --spec-path` flag to specify a custom path location for the problem specifications directory.

**Comment by stkent** [comment]
Perfect, thanks!

**Comment by kytrinyx** [comment]
@stkent when you figure this out, would you mind updating the docs to encode the bits that weren't clear? https://github.com/exercism/docs/blob/master/maintaining-a-track/regenerating-exercise-readmes.md

**Comment by kytrinyx** [comment]
Actually: https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md is probably better.

**Comment by nywilken** [comment]
Sweet,  I'll leave the issue open for a little in case you have any further questions. Otherwise, feel free to close the issue if everything is squared away.

**Comment by stkent** [comment]
https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md looks perfectly clear, I just have trouble finding the right place within the docs apparently!

**Comment by kytrinyx** [comment]
> I just have trouble finding the right place within the docs

This is not your fault. I need to figure out how to organize the docs and provide an overview.
