### ISSUE TITLE
Deprecate "problems" in config.json in favor of "exercises"

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-configlet#7]
For the past three years, the ordering of exercises has been done based on gut feelings and wild guesses. Over time this has proven to work OK-ish, but it's not great. In order to have the ability to support a more structured and systematic approach to ordering problems, we're going to deprecate the simple array of problem slugs in the `config.json` file of each track, and start using a new format, under the key "exercises", documented below:

```
"exercises": [
      {
        "slug": "hello-world" ,
        "difficulty": 1,
        "topics": [
            "control-flow (if-statements)",
            "optional values",
            "text formatting"
        ]
      },
      {
        "difficulty": 3,
        "slug": "anagram",
        "topics": [
            "strings",
            "filtering"
        ]
      },
      {
        "difficulty": 1,
        "slug": "binary",
        "topics": [
            "parsing",
            "transforming"
        ]
      }
    ]
```

We need to update `configlet` so that it accepts both formats, until we can remove "problems" completely.

See https://github.com/exercism/discussions/issues/60 for the full discussion.

**Comment by stkent** [comment]
@kytrinyx I believe this issue can be closed in light of https://github.com/exercism/configlet/pull/16.

**Comment by kytrinyx** [comment]
Yepp! Thanks!
