### ISSUE TITLE
Include a Changelog

### ISSUE THREAD

**Issue by robphoenix** [exercism/v2-configlet#70]
@kytrinyx [here](https://github.com/exercism/configlet/pull/68#issue-255102362)

> We don't have a changelog (I know, I know) 

[Why include a changelog?](http://keepachangelog.com/en/1.0.0/)

Tools to consider:

* [Github-Changelog-Generator](https://github.com/skywinder/Github-Changelog-Generator)
* [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli)

**Comment by kytrinyx** [comment]
I really like the format of the one we have for the CLI: https://github.com/exercism/cli/blob/master/CHANGELOG.md

In particular, I don't include all PRs / commits, only the ones that actually affect people. Also I like that it links to the PR and the human who made the change.

**Comment by robphoenix** [comment]
> I don't include all PRs / commits, only the ones that actually affect people. Also I like that it links to the PR and the human who made the change.

Yeah, I totally agree. ~~Is that handcrafted?~~ [Ah, I see it is](https://github.com/exercism/cli/blob/master/RELEASE.md#update-the-changelog)
Well, maybe we start in a similar way until we find/build a tool suitable for both cli & configlet.

Is it a problem if it doesn't (at least inititally) cover the entire history of the tool?

**Comment by kytrinyx** [comment]
> Is it a problem if it doesn't (at least inititally) cover the entire history of the tool?

No, I think it's totally fine to start where we are.
