### ISSUE TITLE
README generation: Sometimes we'd like different capitalisation of the title

### ISSUE THREAD

**Issue by petertseng** [exercism/v2-configlet#76]
My current example is the README of rna-transcription. The generator writes the title as "Rna Transcription", but it would be better if it were "RNA Transcription" instead. But how do we tell the generator that? I don't have a good solution.

Possible exercises that would benefit: DOT DSL, ETL, OCR Numbers, POV, RNA Transcription, SGF Parsing

Related that should probably go in a different issue: punctuation such as Pascal's Triangle, Diffie-Hellman.

**Comment by nywilken** [comment]
@petertseng have you tried overwriting the readme template for the exercises whose titles you want to preserve; replacing `{{ .Spec.Name }}` with the actual title 

> Each track has a default template in ./config/exercise-readme.go.tmpl, and an exercise may override that template by placing a readme.go.tmpl file in the exercise's .meta directory.

More information on using custom metadata paths can be found at  https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md

**Comment by nywilken** [comment]
@petertseng I believe  you may be able to solve this issue by overwriting the readme template for the exercises whose titles you want to preserve; replacing `{{ .Spec.Name }}` with the actual title 

> Each track has a default template in ./config/exercise-readme.go.tmpl, and an exercise may override that template by placing a readme.go.tmpl file in the exercise's .meta directory.

More information on using custom metadata paths can be found at  https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md

**Comment by petertseng** [comment]
> overwriting the readme template for the exercises whose titles you want to preserve

I don't like asking every track that has these exercises to do that.

That was the selfless answer, and now I also present the the selfish answer: I personally don't want to maintain those extra templates in the tracks I maintain (if I should choose to add them). I want as few custom templates as possible.

**Comment by petertseng** [comment]
that was the selfless answer, and now I also present the the selfish answer: I personally don't want to maintain those extra templates. I want as few custom templates as possible.

**Comment by nywilken** [comment]
I completely understand your line of thinking. In fact, as I was writing my comment I thought to myself that this is probably not a feasible solution given the amount of maintenance involved. So thanks for the feedback. 

I have a few ideas, but for reproducibility purposes they rely on having the preferred title stored in some configuration (friendly title with the proper casing). As titles are currently generated from exercise slugs. I have to do some more thinking on this. 

I assume for consistency that this change would be for all tracks. Is that assumption correct? Or would this be something that could be controlled at the track level?

Sorry for all the questions, just trying to gather thoughts on expectations and possible solutions. 

Thanks

**Comment by petertseng** [comment]
> I assume for consistency that this change would be for all tracks. Is that assumption correct? Or would this be something that could be controlled at the track level?

I think that does make the most sense, as I don't think any track would choose to instead display "Rna Transcription" by default rather than "RNA Transcription".

> I have a few ideas, but for reproducibility purposes they rely on having the preferred title stored in some configuration (friendly title with the proper casing). As titles are currently generated from exercise slugs.

Yes, as just one idea (I haven't thought about others yet) it could be that the preferred title would be stored in e.g. https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/metadata.yml, say in a line that reads `title: "RNA Transcription"`. Probably makes sense to have the field be optional, because for other exercises the default generated title is appropriate.

**Comment by nywilken** [comment]
> the preferred title would be stored in e.g. https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/metadata.yml

Yeah, this would make the most sense but I think there may be an issue for tracks that are overwriting an exercise's metedata via a metadata.yml file. Maybe upon readme generation there could be a check to validate that the problem-specifications metadata and an exercise's local metadata.yml, if it is exist, are in-sync. If the metadata is out of sync it would terminate the generation process with an error indicating that data would be lost.

Another thought I had was to have configlet support some non over-writable metadata within the problem-specification repo. But the above may be the way to go. 

> Probably makes sense to have the field be optional, because for other exercises the default generated title is appropriate.

Yes

**Comment by petertseng** [comment]
> Yeah, this would make the most sense but I think there may be an issue for tracks that are overwriting an exercise's metedata via a metadata.yml file

This is a little scary. Is this an operation that is supported? I have not heard of it, but I will check right now...

```
$ for i in problem-specifications/exercises/*; do e=$(basename "$i"); f1=$i/metadata.yml; for t in tracks/*; do f2=$t/exercises/$e/.meta/metadata.yml; if [ -f $f2 ]; then echo "$t OVERRIDES METADATA of $e"; diff -s $f1 $f2; fi; done ; done
tracks/go OVERRIDES METADATA of error-handling
Files problem-specifications/exercises/error-handling/metadata.yml and tracks/go/exercises/error-handling/.meta/metadata.yml are identical
tracks/go OVERRIDES METADATA of phone-number
Files problem-specifications/exercises/phone-number/metadata.yml and tracks/go/exercises/phone-number/.meta/metadata.yml are identical
tracks/go OVERRIDES METADATA of simple-cipher
Files problem-specifications/exercises/simple-cipher/metadata.yml and tracks/go/exercises/simple-cipher/.meta/metadata.yml are identical
```

I had no idea a track was doing this, but all right, so there exists a track that does do so.

So, I won't try to comment on what happens on the configlet side, but if the problem is tractable on the configlet side, then I'm down to add a `title` field. Luckily the three metadata.yml files are not among the set of exercises that would get a `title` field, so it isn't an immediate problem.

**Comment by petertseng** [comment]
> > the preferred title would be stored in e.g. https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/metadata.yml
>
> Yeah, this would make the most sense but I think there may be an issue for tracks that are overwriting an exercise's metedata via a metadata.yml file

I think (and also taking into consideration what's happening in #65) it can remain an all-or-nothing thing. If a track has a metadata.yml file, all its keys get used, including the presence or absence of a `title:` in the track-specific metadata.yml file, and the file in problem-speifications doesn't need to be read. If the track does not have one, then all the keys take on the values of those in problem-specifications. I don't think any key (`title:` or otherwise) needs to be made non-overridable. I hope what I said makes sense.

The favour I am asking right now: If y'all here are on board with the `title:` field in metadata.yml (you can see what it would look like at https://github.com/exercism/problem-specifications/pull/901), if you could say so.

* If yes, I will work on the documentation that needs to go in https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md
* If no, I can revise https://github.com/exercism/problem-specifications/pull/901 according to any suggestion you may have.

**Comment by nywilken** [comment]
@petertseng it makes sense.  I have a working example of what you described https://github.com/nywilken/exer-configlet/commit/c18a0131f7793660854262ee3cd970a1ca698f1c

But I stopped short because I have a few unanswered questions: 
1. For consistency, would trackler and the website need to change? But it looks like you have that covered. 
2. Do any of the exercises rely on Spec.Name for anything outside of the readme? 
3. If the answer to no. 2 is yes, then should readme templates be updated to use something like `Spec.Title` or `Spec.DisplayTitle`? Defaulting to `Spec.Name` when no title has been provided. 

Questions 2 and 3 are on the configlet side, I just haven't had a moment to dive into all the tracks yet. 

RE: the favour, the use of `title` makes sense to me. However, I have not vetted the change so I can't say confidently that it is simply honoring title over name within Configlet.  @kytrinyx @robphoenix thoughts?

**Comment by kytrinyx** [comment]
I'm late to the party here, but I agree on your proposed tactic of adding a `title` property to the `metadata.yml`.

If the title is empty, we should default the title to `Spec.Name` in the logic for `Spec` (the templates shouldn't have to know about it).

In terms of overriding the problem-specification's `metadata.yml`, I think that any field in `metadata.yml` can be overridden. A plus would be if every field doesn't have to be overridden. If it exists in the generic metadata.yml but not the specific, then it would be great if we fell back to the generic one. This would let us be very selective in how much we override, leaning on existing data where it makes sense to do so.

> For consistency, would trackler and the website need to change?

I think it's most important in the v2 prototype, less-so in trackler since that codebase will be going away as soon as v2 launches.

> Do any of the exercises rely on Spec.Name for anything outside of the readme?

No, the `Spec` was introduced solely for the README generation, and I can't imagine that anyone has had the time to start using it for anything else. I'm OK with being wrong about this. Someone will notice, and I'll apologize to them.
