### ISSUE TITLE
configlet lint: should it exit non-zero if config.json is unparseable as JSON? (it currently exits zero)

### ISSUE THREAD

**Issue by petertseng** [exercism/v2-configlet#77]
https://github.com/exercism/ceylon/pull/50 introduces obviously invalid JSON in config.json (missing comma between properties of an object, and an unclosed opening brace)

In the build, https://travis-ci.org/exercism/ceylon/builds/276065890 we can see

```
$ bin/configlet lint .
-> invalid config config.json -- invalid character '{' after object key:value pair
The command "bin/configlet lint ." exited with 0.
```

configlet has correctly determined that the file is invalid JSON. But then it exits zero. Should it be nonzero instead, so we can be assured that it will only exit zero if the config is valid JSON that also passes lints? It would be helpful for CI if we can be assured this is the case.

**Comment by petertseng** [comment]
EBWODP:

It would be helpful for CI if we can be assured this is the case.

**Comment by nywilken** [comment]
> Should it be nonzero instead

Yes, the issue is on [#L55](https://github.com/exercism/configlet/blob/b4a06de9313ee3f1310b730f8c69f6ea11d6455a/cmd/lint.go#L55)

Thanks for reporting.

**Comment by petertseng** [comment]
Thanks. Consider me a subscriber for knowing when it gets released too (important so I know when I can stop manually verifying a submitted config.json is valid JSON)

**Comment by nywilken** [comment]
@petertseng thanks again for your help and patience. I'm going to loop in @robphoenix & @kytrinyx  in case they have a little bandwidth to cut a release. Otherwise, I should be able to cut a release on Friday.

**Comment by petertseng** [comment]
Also, in case my comment took on too much of a hellfire-and-brimstone tone...

I will admit knowing that I was less-than-optimally helpful (optimally helpful = provide the patch to the problem rather than just reporting it), and so I hope you know I thank you for doing the favour of patching it in my stead.

For the release process, in contrast, I now have no power to be helpful, so in this case I am forced to ask for the favour. Nothing on fire, just a hope that a favour can be fulfilled at some point. Friday will be just great, thank you.

**Comment by nywilken** [comment]
> Also, in case my comment took on too much of a hellfire-and-brimstone tone...

Not at all. I understand where you're coming from and, to be honest, I didn't think too much into the tone of the comment. 

> I will admit knowing that I was less-than-optimally helpful (optimally helpful = provide the patch to the problem rather than just reporting it), and so I hope you know I thank you for doing the favour of patching it in my stead.

I'm glad to help, and I really do appreciate your help and attention to details when it comes to reporting and validating issues - its super helpful. 

If you can do me the favour in testing the [latest release](https://github.com/exercism/configlet/releases/tag/v3.5.1), we can easily call this a favour for a favour 😉

**Comment by petertseng** [comment]
> If you can do me the favour in testing the latest release, we can easily call this a favour for a favour

This I am glad to do. Now if I look at https://travis-ci.org/exercism/ceylon/builds/279014098, I see:

```
$ bin/configlet lint .

-> invalid config config.json -- invalid character '{' after object key:value pair

The command "bin/configlet lint ." exited with 1.
```

and that, as a result, the build was declared a failure.

And this is what we wanted to happen. Thanks!
