### ISSUE TITLE
Verify the presence of a test file

### ISSUE THREAD

**Issue by kytrinyx** [exercism/v2-configlet#8]
@behrtam commented in https://github.com/exercism/xpython/pull/392:

> ./bin/configlet only checks that for every exercises in the config.json there is also an example implementation and vice versa. It doesn't check if there is also a test file for every exercise.

We should actually read the `test_pattern` from the `config.json` file (defaulting to `/test/i` if `test_pattern` isn't defined) and verify this for each exercise.

**Comment by nywilken** [comment]
@kytrinyx I would like to help out with this issue, if it hasn't already been taken. 

I'm working through the code changes and reading the [doc](https://github.com/exercism/docs/blob/9df310839d0d7413aec5915d13758c15c6a3388d/language-tracks/configuration/README.md) to get an understanding of things. Please let me know if there are any other threads I should read through. Thanks.

**Comment by kytrinyx** [comment]
@nywilken that would be great. I don't _think_ there's any more context you need than what is here, but if you get stuck or confused don't hesitate to ask.

**Comment by nywilken** [comment]
@kytrinyx sounds good, thanks.

**Comment by kytrinyx** [comment]
@nywilken I've sent you an invite to the Exercism organization. If/when you accept it, drop a line here so I can assign this issue to you.

**Comment by nywilken** [comment]
@kytrinyx invite accepted, thanks.

**Comment by kytrinyx** [comment]
Welcome ✨ 💛 🌻 💛 ✨

**Comment by nywilken** [comment]
@kytrinyx thanks for the encouraging welcome. I submitted PR #32, as a first pass, to address this issue. I left a few assumptions and remaining tasks in the comments of the PR. Looking forward to the review.

**Comment by kytrinyx** [comment]
Awesome, thanks so much for that!

**Comment by nywilken** [comment]
Closed by #32

**Comment by rpottsoh** [comment]
Looks like this should have closed when #32 was merged.
