### ISSUE TITLE
generate throws illegal number syntax: "-".

### ISSUE THREAD

**Issue by dkinzer** [exercism/v2-configlet#82]
I used a version configlet which I compiled locally on the v3.5.1 tag on a Mac that is running EL Capitan OSX.

Anyway, when I tried to generate a readme for the ruby/palindrome-products exercise (exercism/ruby#728, I got the following error:

```
illegal number syntax: "-" 
```

I was able to bypass this error by updating the ruby track template: exercism/ruby#727, and removing `-` from that file.

I don't know if the issue is with configlet or the template.

**Comment by kytrinyx** [comment]
@dkinzer thanks for reporting this. 🌷 

> I used a version configlet which I compiled locally

I've done the same. I've got v3.5.1 of Configlet, and I updated both `problem-specifications` and the `ruby` repository to the latest master.

When I run the command below, it succeeds in generating the README. (My problem-specifications is not in the default location, so it's safe to ignore that difference).

```
$ configlet generate . --only palindrome-products --spec-path ../../problem-specifications/
```

I wonder what is causing this.

Which version of Go do you have installed?

Mine is:

```
$ go version
go version go1.9 darwin/amd64
```

**Comment by dkinzer** [comment]
Ah, that was it.  I was using go1.5.  After updating and recompiling I do not get errors.  Thanks!

**Comment by kytrinyx** [comment]
Oooh! Yeah 1.5 is pretty old. We support 1.8, 1.9, and "tip"

Thanks for helping get this sorted so quickly! 💙
