### ISSUE TITLE
Update our own README

### ISSUE THREAD

**Issue by tleen** [exercism/v2-configlet#91]
[yo dawg](http://knowyourmeme.com/memes/xzibit-yo-dawg) I heard you like READMEs....

We should probably update our own README to include info on generating READMEs with the configlet tool. I have an outline in the Go track [README](https://github.com/exercism/go#exercism-go-style) that I generated with configlet's README `generate`. We could start with that? 

Happy to do this once I get `tree` done.

**Comment by ilya-khadykin** [comment]
That would be awesome to have this section

**Comment by kytrinyx** [comment]
w00op. Yes, let's have more readmes in our readme!
