### ISSUE TITLE
Update repo description?

### ISSUE THREAD

**Issue by tleen** [exercism/v2-configlet#92]
It may be good to update this repo's description: "Simple verification tool for exercism problem configuration", the tool has become multifaceted. Something more along the lines of "Tool to assist in managing exercism tracks"?

**Comment by kytrinyx** [comment]
Yeah that sounds good. I like

> Tool to assist in managing exercism tracks

I'm changing it now, but if through discussion we decide that we want something else, it's no big deal to update it again.

**Comment by kytrinyx** [comment]
If you are all happy with the new description, go ahead and close this :-)
