### ISSUE TITLE
lint: exercise is not core and has no parents

### ISSUE THREAD

**Issue by NobbZ** [exercism/v2-configlet#96]
An exercise should either be `"core": true` or there should be a `"unlocked_by": ...` present.

Curently a `"core": false` without an `"unlocked_by"` will pass configlets checks and accepted as a fine exercise.

For v1 this doesn't make any difference, but for v2 such an exercise will either mess up the interface or not be accessible, therefore we should avoid such constellations before it is to late!

**Comment by NobbZ** [comment]
As an example you can take a look at PR exercism/bash#93.

**Comment by tleen** [comment]
@NobbZ is a missing "unlocked_by" more or less the same as a `null` "unlocked_by"? (I guess technically it's undefined, but also *falsey*). In which case doesn't that define an exercise as a bonus exercise? 

```javascript
{core: false, unlocked_by: null}
```

**Comment by kytrinyx** [comment]
@tleen @NobbZ yes, these are considered bonus exercises, and are available in v2 as soon as the person submits their first core exercise.

**Comment by NobbZ** [comment]
Ah, I missed that… So a missing (or `null`) `"unlocked_by"` implies to be unlocked by first core… Including `hello-world` or the first after that?

Why not beeing explicit?

Intuitively, I'd consider something that hasn't an unlocked_by field as not unlockable…

**Comment by kytrinyx** [comment]
It's not unlocked by completing the first core, it's unlocked by starting the track (actually submitting your first iteration of something on the track). It's so that people don't get stuck with nothing to do when waiting for their first feedback.

**Comment by NobbZ** [comment]
Ah, okay, I think I understand.

**Comment by Insti** [comment]
This should probably be documented.
